export interface ParsedTerm { raw_term: string; normalized_term: string; family: string; pick3: string[]; pick4: string[]; }
export interface ParsedDreamContract { dream_date: string; dream_label: string; raw_text: string; terms: ParsedTerm[]; }
export type GameType = 'pick3' | 'pick4';
export type BacktestScope = 'single' | 'all-states';
export interface EngineJobOptions { scope: BacktestScope; game_type: GameType; state?: string; lookahead_days: number; terms: 'all' | string[]; }
export interface EngineJobRequest { label: string; game_type: GameType; anchor_date: string; lookahead_days: number; candidates: string[]; state?: string; scope?: 'all-states'; }
export interface EngineHit { candidate: string; draw_date: string; draw_time: string; winning_number: string; match_type: 'exact' | 'box' | string; is_verified?: boolean; source_name?: string; [key: string]: unknown; }
export interface EngineSingleStateResponse { hit_count: number; hit_dates: string[]; hit_draw_times: string[]; summary: string; hits: EngineHit[]; all_draws?: unknown[]; coverage_gaps?: unknown[]; }
export interface EngineAllStatesResponse { scope: 'all-states'; game_type: string; anchor_date: string; lookahead_days: number; candidates: string[]; label: string; overall_hit_count: number; states_attempted: number; states_succeeded: number; states_with_hits: string[]; failed_states: string[]; combined_hits: Array<EngineHit & { state: string }>; results_by_state: Record<string, EngineSingleStateResponse>; coverage_gaps_by_state: Record<string, unknown[]>; }
export type AnyEngineResponse = EngineSingleStateResponse | EngineAllStatesResponse;
export function isAllStatesEngineResponse(r: AnyEngineResponse): r is EngineAllStatesResponse { return (r as EngineAllStatesResponse).scope === 'all-states'; }
export interface DreamHitRecord { candidate: string; draw_date: string; draw_time: string; winning_number: string; match_type: 'exact' | 'box' | string; is_verified: boolean; source_name: string; state: string; game_type: GameType; raw_term: string; normalized_term: string; family: string; anchor_date: string; lookahead_days: number; dream_label: string; dream_date: string; }
export interface DreamTermResult { raw_term: string; normalized_term: string; family: string; game_type: GameType; candidates: string[]; hit_count: number; hits: DreamHitRecord[]; coverage_gaps: unknown[]; states_with_hits: string[]; states_failed: string[]; }
export interface DreamFamilyResult { family: string; game_type: GameType; hit_count: number; hits: DreamHitRecord[]; terms_with_hits: string[]; states_with_hits: string[]; }
export interface DreamBacktestResult { dream_date: string; dream_label: string; raw_text: string; game_type: GameType; scope: BacktestScope; anchor_date: string; lookahead_days: number; total_hit_count: number; exact_hit_count: number; box_hit_count: number; verified_hit_count: number; states_with_hits: string[]; families_with_hits: string[]; terms_with_hits: string[]; all_hits: DreamHitRecord[]; by_term: DreamTermResult[]; by_family: DreamFamilyResult[]; overlapping_candidates: string[]; coverage_gaps_by_state: Record<string, unknown[]>; failed_states: string[]; generated_at: string; }
